Update 끝말잇기.md
MeongJJeong/Coala_exampleForGit pull request #14
Opened 2020-06-29 12:57 UTC by MeongJJeong

hot fix

2020-06-29 16:23 UTC, SnovvyOwl commented
Wow

2020-06-29 16:24 UTC, SnovvyOwl reviewed
이거 어떻게 하는건가요?..

2020-06-30 04:06 UTC, SnovvyOwl approved these changes
이렇게해야하나?

2020-06-30 04:17 UTC, SnovvyOwl requested changes
Test

2020-06-30 04:17 UTC, MeongJJeong commented
오오... 이런느낌으로다가...

2020-06-30 04:21 UTC, SnovvyOwl approved these changes

2020-06-30 04:22 UTC, merged